add_newline = true

[git_branch]
# symbol = "🌱 "

[git_commit]
# tag_symbol = "🔖 "

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false

[nodejs]
format = "via [🤖 $version](bold green) "
